task: kneadings_pendulums

inits:
  fi1: 1.4721305818718418
  v1: 1e-6
  fi2: 1.9044149804862014
  v2: 0

defaultSystem:
  gamma: 0.97
  lambda: 0.2
  k: 0.06

grid:
  first:
    name: gamma
    caption: gamma
    left_n: 300
    right_n: 300
    left_step: 0.01
    right_step: 0.01
  second:
    name: k
    caption: k
    down_n: 300
    up_n: 300
    down_step: 0.01
    up_step: 0.01

kneadings_pendulums:
  dt: 0.001
  n: 200000
  stride: 1
  kneadings_start: 0
  kneadings_end: 16

misc:
  param_to_index:
    gamma: 0
    lambda: 1
    k: 2


  init_res: ignore
  start_eq: [0.0, 0.0, 0.0, 0.0]

  plot_params:
    font_size: 14

output:
  directory: "C:/Lobach4/tu/kneadings-master1/output"
  mask: "kneadings_pendulums2"
  imageExtension: png
  useTimestamp: true
  overwrite: false
  makeSubdir: false

