# Конфигурация для 9-цветной карты типов аттракторов (Stat/Lib/Rot)

task: kneadings_pendulums

# Режим старта:
# Используем separatrix, чтобы анализировать глобальную структуру
# (поведение неустойчивого многообразия седло-фокуса)
#stable_equilibrium старт с уст ср
#manual с рандомной точки
init_mode: manual
inits:
  fi1: 10.5
  v1: -3.0
  fi2: -1.0
  v2: 1.0

# Настройки автоматического старта с сепаратрисы
separatrix_init:
  saddle_focus_rule: phi1_lt_phi2
  branch_rule: phi2_above_eq
  offset_index: 1
  # Базовые параметры, относительно которых строится сетка
  base_params:
    gamma: 0.3
    lambda: 0.1
    k: 0.5

# Центральные параметры системы (центр карты)
defaultSystem:
  gamma: 0.3
  lambda: 0.1
  k: 0.5

# Описание сетки параметров
grid:
  # Горизонтальная ось: коэффициент связи k
  first:
    name: k
    caption: "k"
    left_n: 300
    right_n: 300
    left_step: 0.001
    right_step: 0.001

  # Вертикальная ось: внешнее воздействие gamma
  second:
    name: gamma
    caption: "gamma"
    down_n: 300
    up_n: 300
    down_step: 0.001
    up_step: 0.001

# Настройки вычислительного ядра (CUDA)
kneadings_pendulums:
  dt: 0.01
  # Увеличиваем n до 3.5 млн, чтобы гарантированно пройти транзиенты
  # и накопить статистику для классификации
  n: 5000000
  stride: 1
  # Начинаем анализ только после 15 000 событий, чтобы забыть старт
  kneadings_start: 100000
  # Собираем окно в 2000 событий для поиска периода и типа движения
  kneadings_end: 3000

  use_continuation_mode: True #протягивение аттрактора
  use_9color_mode: True   # ВКЛЮЧАЕМ РЕЖИМ 10 ЦВЕТОВ (Stat/Lib/Rot)
  use_regime_mode: False  # Отключаем ЧБ режим

misc:
  param_to_index:
    gamma: 0
    lambda: 1
    k: 2
  plot_params:
    font_size: 14

output:
  # Путь к папке
  directory: "C:/Lobach4/tu/kneadings-master1/output/attractor_maps"
  mask: "attractor_map_9color"
  imageExtension: png
  useTimestamp: true
  overwrite: false
  makeSubdir: false