task: kneadings_pendulums #код понимает, какую модель использовать

#начальные условия (углы и скорости)
inits:
  fi1: 1.9044149804862014
  v1: 1e-6
  fi2: 1.4721305818718418
  v2: 0

#параметры системы
defaultSystem:
  gamma: 0.97 #постоянное внешнее воздействие
  lambda: 0.2 #коэфф затухания
  k: 0.06 #коэфф связи между маятниками

#описание двумерной сетки параметров
grid:
  #варьируем параметр гамма 300 шагов влево, 300 шагов вправо, шаг 0,01
  first:
    name: gamma
    caption: gamma
    left_n: 300
    right_n: 300
    left_step: 0.01
    right_step: 0.01
  #варьируем параметр k
  second:
    name: k
    caption: k
    down_n: 300
    up_n: 300
    down_step: 0.01
    up_step: 0.01

#численно интегрируется система
kneadings_pendulums:
  dt: 0.001 #д.м. шаг, чтобы численный метод был точным
  n: 200000 #достаточно большое кол-во шагов, чтобы увидеть установившиеся режимы
  stride: 1 #сохраняем состояние системы на каждом шаге интегрирования
  kneadings_start: 0
  kneadings_end: 16 #индекс последнего символа в символьной последовательности


misc:
  #сопоставляет названия параметров с индексами в массивах данных
  param_to_index:
    gamma: 0
    lambda: 1
    k: 2

  # временно: чтобы код не падал, пока не переделаем init-стадию
  init_res: ignore
  start_eq: [0.0, 0.0, 0.0, 0.0]

  #размер текста на картинке
  plot_params:
    font_size: 14

output:
  directory: "C:/Lobach4/tu/kneadings-master1/output"
  mask: "kneadings_pendulums1"
  imageExtension: png
  useTimestamp: true
  overwrite: false
  makeSubdir: false

